name: main

on:
- push
- pull_request

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm run bootstrap
    - run: npm run build
    - run: npm test -- --coverage
      env:
        CI: true
    - uses: codecov/codecov-action@v1
