name: main

on:
  - push
  - pull_request

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npx lerna@4.0.0 exec --npm install
      - run: npx lerna@4.0.0 run build
      - run: npm test -- --coverage
        env:
          CI: true
      - uses: codecov/codecov-action@v1
