name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - run: pnpm install
    - run: changesets/action@v1
      with:
        commit: 'chore: bump version'
        version: pnpm run version
        publish: pnpm run publish
        createGithubReleases: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
